
from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime

# --- USER MODELS ---
class UserBase(BaseModel):
    """The foundation of a User record, shared by Create and Response models."""
    uid: str
    email: str
    role: str = "user" # Default role is 'user' until promoted by admin.
    firstName: str
    lastName: str
    fatherName: str
    mobile: str
    gender: str
    bloodGroup: str
    islandGroup: str
    region: str
    city: str
    barangay: str
    address: str
    hospitalId: Optional[str] = None # Only for Hospital Admins.
    isBanned: bool = False
    createdAt: datetime = Field(default_factory=datetime.now)

class UserCreate(UserBase):
    """Used when the Flutter app sends a new user profile to be saved."""
    pass

class UserResponse(UserBase):
    """The JSON structure returned to the app when fetching user info."""
    pass

# --- HOSPITAL MODELS ---
class HospitalBase(BaseModel):
    """The foundation of a Hospital record."""
    name: str
    email: str
    islandGroup: str
    region: str
    city: str
    barangay: str
    address: str
    contactNumber: str
    latitude: float
    longitude: float
    availableBloodTypes: List[str]
    isActive: bool = True
    createdAt: datetime = Field(default_factory=datetime.now)

class HospitalCreate(HospitalBase):
    """Used for registering a new hospital."""
    pass

class HospitalResponse(HospitalBase):
    """Includes the unique 'id' generated by Firestore."""
    id: str

# --- BLOOD REQUEST MODELS ---
class BloodRequestBase(BaseModel):
    """Represents a transaction of blood (Requesting or Donating)."""
    userId: str
    userName: str
    type: str # 'Request' or 'Donate'
    bloodType: str
    status: str = "pending" # lifecycle: pending -> on progress -> completed/rejected.
    hospitalId: str
    hospitalName: str
    contactNumber: str
    quantity: float
    # New medical fields
    patientName: Optional[str] = None
    patientHospital: Optional[str] = None # Specify where the patient is admitted.
    urgency: Optional[str] = "Regular" # 'Emergency', 'Regular', 'Scheduled'
    hospitalWard: Optional[str] = None
    medicalReason: Optional[str] = None
    lastDonationDate: Optional[str] = None
    # Appointment details (synced with Flutter)
    preferredDate: Optional[str] = None
    preferredTime: Optional[str] = None
    adminMessage: Optional[str] = None # Added to store feedback from Hospital Admins.
    createdAt: datetime = Field(default_factory=datetime.now)

class BloodRequestCreate(BloodRequestBase):
    """Used when a user fills out the Request or Donate form."""
    pass

class BloodRequestResponse(BloodRequestBase):
    """Unique transaction record with ID."""
    id: str

# --- INVENTORY MODELS ---
class InventoryBase(BaseModel):
    """Tracking stock levels for a specific blood type in a specific hospital."""
    blood_type: str
    units: float
    last_updated: datetime = Field(default_factory=datetime.now)

class InventoryCreate(InventoryBase):
    pass

class InventoryResponse(InventoryBase):
    pass

# --- NOTIFICATION MODELS ---
class NotificationBase(BaseModel):
    """In-app alerts sent to users regarding their requests."""
    userId: str
    message: str
    isRead: bool = False
    createdAt: datetime = Field(default_factory=datetime.now)
    type: Optional[str] = None
    title: Optional[str] = None
    body: Optional[str] = None
    requestId: Optional[str] = None

class NotificationCreate(NotificationBase):
    pass

class NotificationResponse(NotificationBase):
    """Unique notification record with ID."""
    id: str





























